// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"ucenter-api/internal/svc"
)

func RegisterHandlers(r *Routes, serverCtx *svc.ServiceContext) {
	register := NewRegisterHandler(serverCtx)

	r.Get("/", register.Register)
}
