// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

type Router struct {
	srv         *rest.Server
	middlewares []rest.Middleware
}

func NewRouter(srv *rest.Server) *Router {
	return &Router{
		srv: srv,
	}
}

func (r *Router) Get(path string, handlerFunc http.HandlerFunc) {
	r.srv.AddRoutes(rest.WithMiddlewares(
		r.middlewares,
		rest.Route{
			Method:  http.MethodGet,
			Handler: handlerFunc,
			Path:    path,
		}),
	)
}

func (r *Router) Post(path string, handlerFunc http.HandlerFunc) {
	r.srv.AddRoutes(rest.WithMiddlewares(
		r.middlewares,
		rest.Route{
			Method:  http.MethodPost,
			Path:    path,
			Handler: handlerFunc,
		}),
	)
}

// todo:没有路径的功能，不同 group 只能区分中间件
func (r *Router) Group() *Router {
	return &Router{
		srv: r.srv,
	}
}

func (r *Router) Use(middwares ...rest.Middleware) {
	r.middlewares = append(r.middlewares, middwares...)
}
